### ISSUE TITLE
Custom variables not expanding

### ISSUE THREAD

**Issue by tiagomjorge** [softprops/serverless-rust#104]
I'm trying to configure the plugin's custom variables like this:

```yaml
custom:
  rust:
    dockerTag: my-tag
    dockerImage: my-image
    dockerPath: ${env:DOCKER_PATH}
```

However, I've noticed that the `dockerPath` is getting passed to the plugin non-expanded. Looking at the plugin's code, it seems like since the plugin is consuming all of the configuration parameters on its constructor, it is reading the values before the serverless framework expands them. I've also tried using a file, like:

```yaml
custom:
  rust:
    ${file(serverless/includes/serverless-rust.yml)}
```

But it also doesn't work, which makes sense, since the plugin is reading the config parameters before the serverless framework has a chance to fill them in. One fix would be to read those variables inside the hooked up functions, instead of inside the constructor.

Does this make sense? Am I missing something?
