### ISSUE TITLE
Allow packaging of static files alongside binary

### ISSUE THREAD

**Issue by dancoates** [softprops/serverless-rust#41]
## 💡 Feature description

It would be nice if it was possible to use the `include` and `exclude` package configuration in `serverless.yml` to choose other files to bundle with the bootstrap binary. For example to include a `.env` file that is then read by the [dotenv crate](https://docs.rs/dotenv/0.14.0/dotenv/) at runtime.

I am sure that there are other use cases for including files other than the binary but that is the one that sprang to mind.

**Comment by softprops** [comment]
That's a good point. I've referred adding features until they are needed or asked for. I'll look into this

**Comment by nosideeffects** [comment]
I was under the impression that this was already supported. How would I add this capability myself for my current serverless project?

**Comment by nickspell** [comment]
An alternative solution to the static file packaging problem is to use [AWS Lambda Layers](https://serverless.com/framework/docs/providers/aws/guide/layers/#aws---layers).
Just put your static files into some directory at the root of your project and create a layer from that. 

Example:
```
myservice
├── static
│   ├── foo.json
├── src
├── serverless.yml
```

In your serverless.yml insert:
```yml
layers:
  mydata:
    path: static
    description: My static json data

```

Deploy one time in order to publish the layer the first time, take its ARN code on the AWS online console and link your lambda to it by again modifying your serverless.yml:
```yml
functions:
  myfunction:
    handler: #...
    layers: 
       - <Version ARN> #e.g. arn:aws:lambda:us-east-1:1234567:layer:mydata:1
     # .....
```

You can now access your files as if they are located in the "/opt" folder of your lambda, e.g.:
```rust
let file = File::open("/opt/foo.json")?;
```

This solution is quite useful especially when you want to share your static data between different lambdas.
