### ISSUE TITLE
"packge: include" does not work?

### ISSUE THREAD

**Issue by ItayGarin** [softprops/serverless-rust#81]
Hey @softprops!

Thanks for making this awesome project!
Really enjoyed following your documentation, and deploying rust lambdas :)

I stumbled across a minor issue that might have something to do with the plugin.
I'd like the include a statically built executable within the output zip artifact.
Though, for some reason, I wasn't able to do so. 

I've tried placing the `include` keyword both in the "global" serverless.yaml scope like so -
```
package:
  individually: true
  include:
    - bin/pdftotext
```

and also in my function scope like so - 

```
functions:
  my-lambda:
  package:
    include:
      - bin/pdftotext
```

FYI - 
I've set dockerPath to ".." since I'm building inside a workspace. Like so - 

```
custom:
  rust:
    dockerPath: ".."
``` 

Is it just my setup? Any thoughts?
