### ISSUE TITLE
Support sccache

### ISSUE THREAD

**Issue by Frederick888** [softprops/serverless-rust#91]
## 💡 Feature description
When building in docker, it'd be nice if [`sccache`](https://github.com/mozilla/sccache) can be configured to use S3, GCS, etc as cache storage.

#### 💻 Basic example

For example, something like this would be nice:
```yaml
custom:
  rust:
    cache:
      s3Bucket: my-cache-bucket
      # not only in remote automated builds, locally I can even use minio
      s3Endpoint: http://local-minio.lan:1234
```
